# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'cycloneShelter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'GoogleMaps'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
  # Pods for cycloneShelter

  target 'cycloneShelterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cycloneShelterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
